### ISSUE TITLE
.env not working

### ISSUE THREAD

**Issue by PierrePetite** [jhortale/react-native-weather#4]
Hey, 

just had a look and came along the following issue: I have added the API-Key into the .env like this: API_KEY=12345678 - this also reflects the whole content of the file. But still it gives me: 

utils/useWeather.js: /Documents/expo-weather-app 3.0/react-native-weather/utils/useWeather.js: Try to import dotenv variable "API_KEY" which is not defined in any .env files.
  1 | import { useState, useEffect } from "react";
> 2 | import { API_KEY } from "react-native-dotenv";
    |          ^^^^^^^
  3 | import axios from "axios";
  4 | import { storeWeather, getWeather } from "./storeWeather";
  5 | import useGeoLocation from "./useGeoLocation";

ABI37_0_0RCTFatal
__37-[ABI37_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start

**Comment by jhortale** [comment]
Hi Pierre,

Did you create your account at [Open Weather Map API](https://openweathermap.org/api) and generated your private API_KEY?

They will send your API KEY by email. After that put your key in the .env.example and rename it to .env

**Comment by PierrePetite** [comment]
Yes, did that. Had an account from previous projects. Hm, strange. Did it exactly as you mentioned. Weired.

**Comment by jhortale** [comment]
I just cloned this repo again, install all the dependencies with `npm i` after that made a copy of `.env.example` to `.env`, started the project with `yarn start` and put my API KEY and it worked fine on the web version, on IOS simulator and on the expo app in my iPhone as well.
